### PR TITLE
Update addon_products_sle.pm

### PR DESCRIPTION
**Pull request by dzedro**

### CODE REVIEW

**Comment by coolo** [comment]
Note that https://bugzilla.suse.com/show_bug.cgi?id=913099 changes this for SLE12 - and this should most likely also be in SLE11 as this is really also a problem for users.

**Comment by dzedro** [comment]
So should I close this request for SLE 11 ?

**Comment by coolo** [comment]
well, this PR is just a traning excersise and should be closed. IMO: talk to Ladis

**Comment by coolo** [comment]
(training in using github I should add)

**Comment by dzedro** [comment]
Ladislav will fix it also in SLE 11, closing this PR.

**Pull request closed without merging**
